name: Conda Build and Upload

on:
  release:
    types: [published]

jobs:
  build:
    name: Conda
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
        auto-update-conda: true
        python-version: '3.x'
    - name: Build and upload conda package
      shell: bash -l {0}
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        CONDA_BLD_PATH=$HOME/conda-bld
        export CONDA_BLD_PATH
        conda install --yes --quiet conda-build conda-verify
        conda install --yes --quiet anaconda-client
        conda build conda.recipe/
        anaconda -t $ANACONDA_TOKEN upload $(conda build conda.recipe/ --output)
